version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  caixa:
    build:
      context: .
      dockerfile: caixa/Dockerfile
    command: python app.py
    volumes:
      - ./caixa:/app
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  cozinha:
    build:
      context: .
      dockerfile: cozinha/Dockerfile
    command: python -u app.py 
    volumes:
      - ./cozinha:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  cozinha_api:
    build:
      context: .
      dockerfile: cozinha/Dockerfile
    command: python -u api.py
    volumes:
      - ./cozinha:/app
    ports:
      - "5001:5001"
    depends_on:
      - cozinha

  estoque:
    build:
      context: .
      dockerfile: estoque/Dockerfile
    command: python -u app.py
    volumes:
      - ./estoque:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  estoque_api:
    build:
      context: .
      dockerfile: estoque/Dockerfile
    command: python -u api.py
    volumes:
      - ./estoque:/app
    ports:
      - "5002:5002"
    depends_on:
      - estoque